# Generated by Django 5.2.8 on 2026-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="log",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="logs/proof/"),
        ),
        migrations.AddField(
            model_name="log",
            name="verification_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
